<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign Up</name>
   <tag></tag>
   <elementGuidId>04138725-9d50-4c17-af8f-24ff4e3762a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ml-3.btn.btn-primary.text-white.rounded-pill</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/nav/div/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f1ec187-1721-4b5b-b3fc-a23d8a696157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>3c894633-154f-4ccc-b936-ab6d68a5854e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-3 btn btn-primary text-white rounded-pill</value>
      <webElementGuid>c52e0145-c606-4544-9a01-d059fcebf95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-category</name>
      <type>Main</type>
      <value>user-interaction</value>
      <webElementGuid>71602176-08a7-40e3-991e-babc77e2277c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-conversion</name>
      <type>Main</type>
      <value>micro</value>
      <webElementGuid>9e2b54ad-f5f9-4223-b892-dbdfe72e25b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-section</name>
      <type>Main</type>
      <value>marketing</value>
      <webElementGuid>99f79311-3cd4-419b-a7a8-4e84c437d906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>signup-click</value>
      <webElementGuid>42228697-1579-4d01-b69e-7218fbf69a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-details</name>
      <type>Main</type>
      <value>large-viewport</value>
      <webElementGuid>fc1e567c-34a4-4d2a-84f3-5dc655ec8b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up</value>
      <webElementGuid>36758c6d-f135-449a-97b6-3fd91dd07312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/nav[@class=&quot;py-3 bb-primary-color-override navbar-dark navbar navbar-expand-md navbar-light&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;d-none d-md-block text-right&quot;]/a[@class=&quot;ml-3 btn btn-primary text-white rounded-pill&quot;]</value>
      <webElementGuid>a02c7667-6089-4137-8d19-f88df01bfcb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/nav/div/div[2]/a[2]</value>
      <webElementGuid>64fbd0ea-669c-4ee2-a676-010d7275b1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Sign Up')])[2]</value>
      <webElementGuid>64a2f59c-681e-4ca2-854a-b8b4e4d9540b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/following::a[1]</value>
      <webElementGuid>7cd35245-0492-4208-a955-103aab31e50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Made'])[2]/following::a[2]</value>
      <webElementGuid>dcd2ff5d-bed3-43eb-b057-ee2c0b147121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bargain Box is the affordably delicious choice for any household.'])[1]/preceding::a[1]</value>
      <webElementGuid>910187e9-786c-4e61-97a6-54680bc44102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build your Bargain Box to suit your needs!'])[1]/preceding::a[1]</value>
      <webElementGuid>b82c8477-2857-47d9-a0b3-2b32ed98fe06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/')])[21]</value>
      <webElementGuid>03123b56-5656-4e50-b452-8d536a8f6b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]</value>
      <webElementGuid>edb81a88-f3f9-4749-8053-e9fac8be0ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and (text() = 'Sign Up' or . = 'Sign Up')]</value>
      <webElementGuid>b1bd22e8-3d09-405b-a649-c2065b89ec53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
