<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User logged out_Password</name>
   <tag></tag>
   <elementGuidId>cccfb222-4163-4792-aa93-5b457766ae80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a705345d-7df5-663a-5089-bc28e2ff3667</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='a705345d-7df5-663a-5089-bc28e2ff3667']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13797022-109d-478e-9b08-17e159379ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cd7574b1-1f64-4ee9-8d4c-a1ae9da0005f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3e39e89c-4425-4588-93f8-24c257ee99b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>********</value>
      <webElementGuid>88fb0c9d-26ef-4917-8ffd-68162b6c41fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>94b1f28f-ae96-43c3-af5b-5b7bdf5af6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a705345d-7df5-663a-5089-bc28e2ff3667</value>
      <webElementGuid>e027f49f-7208-49d9-ac03-1679187674de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a705345d-7df5-663a-5089-bc28e2ff3667&quot;)</value>
      <webElementGuid>e7496ac0-43a0-4658-a648-14c25053bed3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a705345d-7df5-663a-5089-bc28e2ff3667']</value>
      <webElementGuid>2739009b-17dd-45ce-88cb-1bb7a6837a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User logged out.'])[1]/following::input[2]</value>
      <webElementGuid>06adc7b4-7bee-4f44-8a56-505eb0c2cf23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample App'])[2]/following::input[2]</value>
      <webElementGuid>2b339173-ac96-432e-b36b-5284d45da4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/preceding::input[1]</value>
      <webElementGuid>95b81d94-6ec4-479f-8ba2-6cbd9e036372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>fbff8529-888e-45c5-8891-e179873ffe12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = '********' and @name = 'Password' and @id = 'a705345d-7df5-663a-5089-bc28e2ff3667']</value>
      <webElementGuid>8bf6ea58-9d93-4c09-8a32-d20b56f8ac05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
