<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User logged out_UserName</name>
   <tag></tag>
   <elementGuidId>03101a75-2207-4a76-8aca-1b24b0aeef47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#23acf6d7-cc5b-5aa6-5fdc-98e45418b075</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='23acf6d7-cc5b-5aa6-5fdc-98e45418b075']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84c756bb-7f76-40d5-9c31-4209a5709d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9f18eccb-73fa-4d3e-bbc9-23ee58b99d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2a1b74c-6c69-462e-a0ef-6b319771c2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User Name</value>
      <webElementGuid>ce8ee49a-54f2-46f7-b63d-0feb16424e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserName</value>
      <webElementGuid>44226e8d-cf3b-4878-bb53-864f2fead82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>23acf6d7-cc5b-5aa6-5fdc-98e45418b075</value>
      <webElementGuid>a34cadaa-b152-4e66-bbd0-b0bad2cc0b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;23acf6d7-cc5b-5aa6-5fdc-98e45418b075&quot;)</value>
      <webElementGuid>a7be41c6-273c-46f5-9a02-ae6e4d93aad7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='23acf6d7-cc5b-5aa6-5fdc-98e45418b075']</value>
      <webElementGuid>3d9ec300-29ef-4352-b0a1-bbe145d4aa89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User logged out.'])[1]/following::input[1]</value>
      <webElementGuid>fb714235-da8e-4710-867f-4182bdedadf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample App'])[2]/following::input[1]</value>
      <webElementGuid>008501d0-1644-4fbb-988c-dc4ea05c5b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/preceding::input[2]</value>
      <webElementGuid>156494fc-6f4c-4063-b571-37532399202d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f25c9288-8a73-4eaf-ac28-fff1e271fea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'User Name' and @name = 'UserName' and @id = '23acf6d7-cc5b-5aa6-5fdc-98e45418b075']</value>
      <webElementGuid>becbbe50-2814-4d3d-8560-5a287d8d3d4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
